name: apple_disease
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  flutter_tflite: ^1.0.1
  get: 4.6.6
  image_picker: ^0.8.5+3
  shared_preferences: 2.2.2
  supabase_flutter: 2.3.4
  loading_animation_widget: ^1.2.1
  flutter: 
    sdk: flutter
  http: ^1.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: MyCustomFont
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
  assets: 
    - assets/onbording/images.jpg
    - assets/models/blurmodel.tflite
    - assets/models/applediseasemodel.tflite
    - assets/label/apple.txt
    - assets/label/blur.txt
  uses-material-design: true

